services:
  frontend:
    image: telware/frontend

    build:
      context: ./app
      dockerfile: prod.Dockerfile

    ports:
      - 8080:80

    environment:
      - NODE_ENV=${NODE_ENV:-production}


  
  