module.exports = {
  collectCoverage: false,
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/*.d.ts",
    "!**/vendor/**",
    "!src/**/*Demo.tsx",
  ],
  coverageDirectory: "coverage",
  testEnvironment: "jest-fixed-jsdom",
  transform: {
    ".(ts|tsx)": "babel-jest",
  },
  moduleNameMapper: {
    "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    "\\.(jpg|jpeg|png|gif|webp|svg)$": "<rootDir>/src/mocks/fileMock.ts",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@inputs/(.*)$": "<rootDir>/src/components/inputs/$1",
    "^@mocks/(.*)$": "<rootDir>/src/mocks/$1",
    "^@features/(.*)$": "<rootDir>/src/features/$1",
    "^@pages/(.*)$": "<rootDir>/src/pages/$1",
    "^@constants$": "<rootDir>/src/constants",
  },
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/coverage",
    "package.json",
    "src/main.tsx",
    "src/App.tsx",
    "src/mocks/",
    "reportWebVitals.ts",
    "jest.setup.ts",
    "index.tsx",
  ],
  setupFiles: ["dotenv/config", "./jest.polyfills.ts"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  testEnvironmentOptions: {
    customExportConditions: [""],
  },
};
